# Generated by p4alpha.flatten.flatten -- DO NOT EDIT BY HAND.
# Source: src/p4alpha/core/execution.py, core/fair_value.py, core/indicators.py + src/p4alpha/strategies/round1.py.
# Regenerate with: python -m p4alpha.flatten.flatten
# Competition-legal single file: stdlib only, plus the runtime-injected
# `datamodel` module (PLAN.md §7). Default construction (Trader())
# is the only path prosperity4bt's CLI ever calls; any opt-in
# constructor flag below is dead on that path by design.

from __future__ import annotations

# --- src/p4alpha/core/execution.py ---
from collections.abc import Sequence

_SIDES = ("buy", "sell")


def position_tier_size(
    deviation: float,
    tiers: Sequence[tuple[float, int]],
    *,
    position: int,
    limit: int,
    side: str,
) -> int:
    """Order size for a signal of magnitude `deviation` (e.g. an absolute
    z-score), given a caller-supplied, strictly-ascending-by-threshold
    list of (deviation_threshold, order_size) tiers: use the order_size
    of the highest threshold not exceeding `deviation` (0 if `deviation`
    is below every tier's threshold). The chosen size is then clamped to
    respect the position limit: for side='buy', capped at
    max(0, limit - position); for side='sell', capped at
    max(0, position + limit). Returns a non-negative quantity; the
    caller applies the sign for a sell order.

    Raises ValueError if:
    - side is not 'buy' or 'sell'
    - tiers is empty
    - tiers is not strictly ascending by threshold (tiers[i][0] must be >
      tiers[i-1][0] for all i > 0)
    - any tier's order_size is negative
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if not tiers:
        raise ValueError("tiers must not be empty")

    size = 0
    previous_threshold = None
    for threshold, order_size in tiers:
        if previous_threshold is not None and threshold <= previous_threshold:
            raise ValueError("tiers must be strictly ascending by threshold")
        if order_size < 0:
            raise ValueError("tier order_size must not be negative")
        previous_threshold = threshold
        if deviation >= threshold:
            size = order_size

    if side == "buy":
        room = max(0, limit - position)
    else:
        room = max(0, position + limit)
    return min(size, room)


def exposure_capped_size(
    candidate_quantity: int,
    *,
    current_exposure: float,
    cap: float,
) -> int:
    """Clamp a candidate signed order quantity so current_exposure plus its
    contribution never pushes an aggregate exposure figure beyond +-cap, in
    whichever direction candidate_quantity moves it (positive grows
    exposure, negative shrinks it). Generalises position_tier_size's own
    limit clamp from a caller's single integer position to an externally
    computed float exposure (e.g. a portfolio's net delta to a correlated
    underlying, stacked across several instruments a single instrument's
    own position limit cannot bound; added in Stage 5, STATE.md decisions
    log, for strategies/round3.py's correlation-stacking exposure cap).

    Returns 0 if current_exposure already meets or exceeds the cap in the
    same direction as candidate_quantity. Preserves candidate_quantity's
    sign; magnitude only ever shrinks, never grows. Room is truncated
    toward zero (int()) rather than rounded, since exposure is a
    fractional delta-weighted figure but order quantity is integral, and
    truncating is the direction that never lets the cap be exceeded.

    Raises ValueError if cap <= 0.
    """
    if cap <= 0:
        raise ValueError(f"cap must be > 0, got {cap}")

    if candidate_quantity > 0:
        room = max(0.0, cap - current_exposure)
        return min(candidate_quantity, int(room))
    if candidate_quantity < 0:
        room = max(0.0, cap + current_exposure)
        return -min(-candidate_quantity, int(room))
    return 0


def threshold_take_price(
    fair_value: float,
    market_price: float,
    side: str,
    threshold: float,
) -> float | None:
    """The price to send a marketable (spread-crossing) order at, when
    `market_price` (the *opposing* side's best quote: the best ask when
    side='buy', the best bid when side='sell') is mispriced against
    `fair_value` by more than `threshold`. Returns None when the edge
    does not clear the threshold (no order should be sent).

    For side='buy': the opportunity exists when
    market_price <= fair_value - threshold (the ask is cheap enough
    relative to fair value); if so, return market_price (join the ask
    exactly, guaranteeing a fill without paying more than necessary).
    For side='sell': symmetric, opportunity when
    market_price >= fair_value + threshold; return market_price.

    Raises ValueError if side is not 'buy' or 'sell', or if threshold < 0.
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if threshold < 0:
        raise ValueError("threshold must not be negative")

    if side == "buy":
        if market_price <= fair_value - threshold:
            return market_price
        return None

    if market_price >= fair_value + threshold:
        return market_price
    return None


def quote_one_tick_better(best_bid: int, best_ask: int, side: str, *, tick: int = 1) -> int:
    """Price one `tick` inside the current best quote on `side`, to
    queue-jump resting orders for a passive (non-crossing) fill.

    For side='buy': candidate = best_bid + tick. If candidate >= best_ask
    (improving would cross or lock the book), fall back to
    best_ask - tick instead. Then clamp the result to be no worse than
    best_bid (max(result, best_bid)) -- i.e. if even the fallback retreats
    below the current best bid, just join the best bid instead of
    quoting worse than the existing market.
    For side='sell': symmetric -- candidate = best_ask - tick, fall back
    to best_bid + tick if candidate <= best_bid, then clamp to
    min(result, best_ask).

    Raises ValueError if best_bid >= best_ask (crossed/locked book,
    malformed input), if side is not 'buy'/'sell', or if tick <= 0.
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if best_bid >= best_ask:
        raise ValueError(f"crossed or locked book: best_bid={best_bid} >= best_ask={best_ask}")
    if tick <= 0:
        raise ValueError("tick must be positive")

    if side == "buy":
        candidate = best_bid + tick
        if candidate >= best_ask:
            candidate = best_ask - tick
        return max(candidate, best_bid)

    candidate = best_ask - tick
    if candidate <= best_bid:
        candidate = best_bid + tick
    return min(candidate, best_ask)


# --- src/p4alpha/core/fair_value.py ---
def naive_mid(bids: dict[int, int], asks: dict[int, int]) -> float | None:
    if not bids or not asks:
        return None
    best_bid = max(bids)
    best_ask = min(asks)
    return (best_bid + best_ask) / 2


def _outer_price(levels: dict[int, int], *, prefer_max_price: bool) -> int:
    max_volume = max(levels.values())
    tied = [price for price, volume in levels.items() if volume == max_volume]
    return max(tied) if prefer_max_price else min(tied)


def outer_anchor(bids: dict[int, int], asks: dict[int, int]) -> float | None:
    if not bids or not asks:
        return None
    bid_price = _outer_price(bids, prefer_max_price=True)
    ask_price = _outer_price(asks, prefer_max_price=False)
    return (bid_price + ask_price) / 2


def two_layer_fair_value(
    bids: dict[int, int],
    asks: dict[int, int],
    *,
    max_inner_deviation: float,
) -> float | None:
    anchor = outer_anchor(bids, asks)
    if anchor is None:
        return None
    inner = naive_mid(bids, asks)
    if inner is not None and abs(inner - anchor) <= max_inner_deviation:
        return (anchor + inner) / 2
    return anchor


# --- src/p4alpha/core/indicators.py ---
from collections import deque
from collections.abc import Sequence
from math import sqrt


class EMA:
    """Exponential moving average, O(1) per update, with an optional pre-feed
    warm start (successive updates over historical values before live use).
    """

    def __init__(self, span: float, pre_feed: Sequence[float] = ()) -> None:
        if span <= 1:
            raise ValueError("span must be > 1")
        self._alpha = 2.0 / (span + 1.0)
        self._value: float | None = None
        for v in pre_feed:
            self.update(v)

    def update(self, value: float) -> float:
        if self._value is None:
            self._value = value
        else:
            self._value += self._alpha * (value - self._value)
        return self._value

    @property
    def value(self) -> float | None:
        return self._value


class RollingMeanStd:
    """Fixed-window rolling mean/std (population std), O(1) per update via a
    running sum and sum-of-squares alongside a bounded deque of raw values.
    """

    def __init__(self, window: int) -> None:
        if window < 2:
            raise ValueError("window must be >= 2")
        self._window = window
        self._values: deque[float] = deque(maxlen=window)
        self._sum = 0.0
        self._sum_sq = 0.0

    def update(self, value: float) -> None:
        if len(self._values) == self._window:
            departing = self._values[0]
            self._sum -= departing
            self._sum_sq -= departing * departing
        self._values.append(value)
        self._sum += value
        self._sum_sq += value * value

    @property
    def ready(self) -> bool:
        return len(self._values) == self._window

    @property
    def mean(self) -> float | None:
        if not self._values:
            return None
        return self._sum / len(self._values)

    @property
    def std(self) -> float | None:
        n = len(self._values)
        if n < 2:
            return None
        mean = self._sum / n
        variance = max(0.0, self._sum_sq / n - mean * mean)
        return sqrt(variance)


class ZScore:
    """Rolling z-score built on RollingMeanStd; None until the window is
    full and has non-zero spread.
    """

    def __init__(self, window: int) -> None:
        self._stats = RollingMeanStd(window)

    def update(self, value: float) -> float | None:
        self._stats.update(value)
        std = self._stats.std
        if not self._stats.ready or std is None or std == 0.0:
            return None
        return (value - self._stats.mean) / std


class LagACF:
    """Rolling lag-k autocorrelation over a fixed window of (x[t], x[t-k])
    pairs, O(1) per update via running sums, no rescan of the window.
    """

    def __init__(self, window: int, lag: int) -> None:
        if lag < 1:
            raise ValueError("lag must be >= 1")
        if window < 2:
            raise ValueError("window must be >= 2")
        self._lag = lag
        self._history: deque[float] = deque(maxlen=lag + 1)
        self._pairs: deque[tuple[float, float]] = deque(maxlen=window)
        self._sum_x = 0.0
        self._sum_y = 0.0
        self._sum_xy = 0.0
        self._sum_x2 = 0.0
        self._sum_y2 = 0.0

    def update(self, value: float) -> float | None:
        self._history.append(value)
        if len(self._history) <= self._lag:
            return None

        lagged = self._history[0]

        if len(self._pairs) == self._pairs.maxlen:
            old_x, old_y = self._pairs[0]
            self._sum_x -= old_x
            self._sum_y -= old_y
            self._sum_xy -= old_x * old_y
            self._sum_x2 -= old_x * old_x
            self._sum_y2 -= old_y * old_y

        self._pairs.append((value, lagged))
        self._sum_x += value
        self._sum_y += lagged
        self._sum_xy += value * lagged
        self._sum_x2 += value * value
        self._sum_y2 += lagged * lagged

        n = len(self._pairs)
        if n < 2:
            return None

        mean_x = self._sum_x / n
        mean_y = self._sum_y / n
        cov = self._sum_xy / n - mean_x * mean_y
        var_x = max(0.0, self._sum_x2 / n - mean_x * mean_x)
        var_y = max(0.0, self._sum_y2 / n - mean_y * mean_y)
        denom = sqrt(var_x * var_y)
        if denom == 0.0:
            return None
        return cov / denom


# --- src/p4alpha/strategies/round1.py ---
import json

from datamodel import Order


ASH = "ASH_COATED_OSMIUM"
ROOT = "INTARIAN_PEPPER_ROOT"

# Confirmed 2026-07-18 (STATE.md decisions log): prosperity4bt.data.LIMITS
# lists round-5 products only; ASH and ROOT fall through to
# DEFAULT_POSITION_LIMIT = 50.
POSITION_LIMIT = 50

# ROOT: docs/results/round1/regime.md, all three days: slope 0.001000/tick
# exactly, R^2 >= 0.9999. resid_std 2.0-2.4; ceiling buffer covers ~2x that.
ROOT_SLOPE = 0.001
ROOT_CEILING_BUFFER = 5.0

# ROOT_SLOPE is hard-coded from research, not re-estimated live (a few-tick
# live fit would be noisier than trusting an identical-to-4-decimals figure
# already confirmed on all three research days). As a safety net against a
# future day where the trend does not hold, the loader halts (stops taking
# new positions, holds whatever is already accumulated) if the realised mid
# ever strays this far from the projected fair value. Calibrated against
# the largest realised deviation actually observed on any research day
# (12.10, docs/results/round1/backtest.md leave-one-day-out section), with
# roughly 2.5x margin so normal noise never trips it.
ROOT_DEVIATION_GUARD = 30.0

# ASH: docs/results/round1/regime.md z-score (window=50) percentile table,
# calibrated on the two-layer fair value (the exact signal z-scored below,
# not raw mid_price, a distinct and more volatile-tailed distribution: see
# the regime.md calibration-basis note and STATE.md decisions log for the
# mismatch this replaced). Consistent across all three days: p90
# ~1.96-1.99, p95 ~2.27-2.29, p99 ~2.84-2.90. Tier sizes scale toward
# POSITION_LIMIT at the extreme tier.
ASH_ZSCORE_WINDOW = 50
ASH_TIERS = [(2.0, 10), (2.3, 25), (2.9, 50)]
ASH_EXTREME_THRESHOLD = 2.9

# docs/results/round1/book_shape.md: pooled 90th percentile of
# |naive_mid - outer_anchor| across all three days is 1.5; within that,
# the inner touch is treated as confirming the outer anchor.
ASH_MAX_INNER_DEVIATION = 1.5


def _book(state, product: str) -> tuple[dict[int, int], dict[int, int]]:
    depth = state.order_depths.get(product)
    if depth is None:
        return {}, {}
    bids = dict(depth.buy_orders)
    asks = {price: abs(qty) for price, qty in depth.sell_orders.items()}
    return bids, asks


def _trade_root(state, trader_data: dict) -> list[Order]:
    if trader_data.get("root_guard_tripped"):
        return []

    bids, asks = _book(state, ROOT)
    if not bids or not asks:
        return []

    mid = naive_mid(bids, asks)
    if mid is None:
        return []

    if trader_data.get("root_start_price") is None:
        trader_data["root_start_price"] = mid
        trader_data["root_start_timestamp"] = state.timestamp

    elapsed = state.timestamp - trader_data["root_start_timestamp"]
    fair_value = trader_data["root_start_price"] + ROOT_SLOPE * elapsed

    if abs(mid - fair_value) > ROOT_DEVIATION_GUARD:
        trader_data["root_guard_tripped"] = True
        return []

    ceiling = fair_value + ROOT_CEILING_BUFFER

    position = state.position.get(ROOT, 0)
    room = POSITION_LIMIT - position
    if room <= 0:
        return []

    orders = []
    for price in sorted(asks):
        if price > ceiling or room <= 0:
            break
        take = min(asks[price], room)
        orders.append(Order(ROOT, price, take))
        room -= take

    return orders


def _trade_ash(
    state,
    trader_data: dict,
    *,
    tiers: list[tuple[float, int]] = ASH_TIERS,
    extreme_threshold: float = ASH_EXTREME_THRESHOLD,
) -> list[Order]:
    """tiers/extreme_threshold default to the pooled-across-all-three-days
    research figures; overridable so docs/results/round1/backtest.md's
    leave-one-day-out check can drive this with tiers calibrated on only
    the other two days, without touching the module-level constants the
    competition submission actually runs with.
    """
    bids, asks = _book(state, ASH)
    if not bids or not asks:
        return []

    tick_fair_value = two_layer_fair_value(bids, asks, max_inner_deviation=ASH_MAX_INNER_DEVIATION)
    if tick_fair_value is None:
        return []

    history = trader_data.get("ash_history", [])
    stats = RollingMeanStd(ASH_ZSCORE_WINDOW)
    for value in history:
        stats.update(value)
    stats.update(tick_fair_value)

    history.append(tick_fair_value)
    trader_data["ash_history"] = history[-ASH_ZSCORE_WINDOW:]

    if not stats.ready or stats.std is None or stats.std == 0.0:
        return []

    # The reversion target is the rolling mean, not this tick's own fair
    # value: comparing the current touch against itself would never show
    # an edge, since tick_fair_value is derived from that same touch.
    reversion_mean = stats.mean
    z = (tick_fair_value - reversion_mean) / stats.std

    deviation = abs(z)
    side = "sell" if z > 0 else "buy"  # price above the reversion mean -> sell; below -> buy
    position = state.position.get(ASH, 0)

    size = position_tier_size(deviation, tiers, position=position, limit=POSITION_LIMIT, side=side)
    if size <= 0:
        return []

    best_bid = max(bids)
    best_ask = min(asks)
    quantity = size if side == "buy" else -size

    if deviation >= extreme_threshold:
        market_price = best_ask if side == "buy" else best_bid
        take_price = threshold_take_price(reversion_mean, market_price, side, threshold=0.0)
        if take_price is None:
            return []
        return [Order(ASH, int(round(take_price)), quantity)]

    quote_price = quote_one_tick_better(best_bid, best_ask, side)
    return [Order(ASH, quote_price, quantity)]


class Trader:
    def run(self, state):
        trader_data = json.loads(state.traderData) if state.traderData else {}

        orders: dict[str, list[Order]] = {}

        root_orders = _trade_root(state, trader_data)
        if root_orders:
            orders[ROOT] = root_orders

        ash_orders = _trade_ash(state, trader_data)
        if ash_orders:
            orders[ASH] = ash_orders

        return orders, 0, json.dumps(trader_data)
