# Generated by p4alpha.flatten.flatten -- DO NOT EDIT BY HAND.
# Source: src/p4alpha/core/execution.py, core/fair_value.py, core/indicators.py + src/p4alpha/strategies/round5.py.
# Regenerate with: python -m p4alpha.flatten.flatten
# Competition-legal single file: stdlib only, plus the runtime-injected
# `datamodel` module (PLAN.md §7). Default construction (Trader())
# is the only path prosperity4bt's CLI ever calls; any opt-in
# constructor flag below is dead on that path by design.

from __future__ import annotations

# --- src/p4alpha/core/execution.py ---
from collections.abc import Sequence

_SIDES = ("buy", "sell")


def position_tier_size(
    deviation: float,
    tiers: Sequence[tuple[float, int]],
    *,
    position: int,
    limit: int,
    side: str,
) -> int:
    """Order size for a signal of magnitude `deviation` (e.g. an absolute
    z-score), given a caller-supplied, strictly-ascending-by-threshold
    list of (deviation_threshold, order_size) tiers: use the order_size
    of the highest threshold not exceeding `deviation` (0 if `deviation`
    is below every tier's threshold). The chosen size is then clamped to
    respect the position limit: for side='buy', capped at
    max(0, limit - position); for side='sell', capped at
    max(0, position + limit). Returns a non-negative quantity; the
    caller applies the sign for a sell order.

    Raises ValueError if:
    - side is not 'buy' or 'sell'
    - tiers is empty
    - tiers is not strictly ascending by threshold (tiers[i][0] must be >
      tiers[i-1][0] for all i > 0)
    - any tier's order_size is negative
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if not tiers:
        raise ValueError("tiers must not be empty")

    size = 0
    previous_threshold = None
    for threshold, order_size in tiers:
        if previous_threshold is not None and threshold <= previous_threshold:
            raise ValueError("tiers must be strictly ascending by threshold")
        if order_size < 0:
            raise ValueError("tier order_size must not be negative")
        previous_threshold = threshold
        if deviation >= threshold:
            size = order_size

    if side == "buy":
        room = max(0, limit - position)
    else:
        room = max(0, position + limit)
    return min(size, room)


def exposure_capped_size(
    candidate_quantity: int,
    *,
    current_exposure: float,
    cap: float,
) -> int:
    """Clamp a candidate signed order quantity so current_exposure plus its
    contribution never pushes an aggregate exposure figure beyond +-cap, in
    whichever direction candidate_quantity moves it (positive grows
    exposure, negative shrinks it). Generalises position_tier_size's own
    limit clamp from a caller's single integer position to an externally
    computed float exposure (e.g. a portfolio's net delta to a correlated
    underlying, stacked across several instruments a single instrument's
    own position limit cannot bound; added in Stage 5, STATE.md decisions
    log, for strategies/round3.py's correlation-stacking exposure cap).

    Returns 0 if current_exposure already meets or exceeds the cap in the
    same direction as candidate_quantity. Preserves candidate_quantity's
    sign; magnitude only ever shrinks, never grows. Room is truncated
    toward zero (int()) rather than rounded, since exposure is a
    fractional delta-weighted figure but order quantity is integral, and
    truncating is the direction that never lets the cap be exceeded.

    Raises ValueError if cap <= 0.
    """
    if cap <= 0:
        raise ValueError(f"cap must be > 0, got {cap}")

    if candidate_quantity > 0:
        room = max(0.0, cap - current_exposure)
        return min(candidate_quantity, int(room))
    if candidate_quantity < 0:
        room = max(0.0, cap + current_exposure)
        return -min(-candidate_quantity, int(room))
    return 0


def threshold_take_price(
    fair_value: float,
    market_price: float,
    side: str,
    threshold: float,
) -> float | None:
    """The price to send a marketable (spread-crossing) order at, when
    `market_price` (the *opposing* side's best quote: the best ask when
    side='buy', the best bid when side='sell') is mispriced against
    `fair_value` by more than `threshold`. Returns None when the edge
    does not clear the threshold (no order should be sent).

    For side='buy': the opportunity exists when
    market_price <= fair_value - threshold (the ask is cheap enough
    relative to fair value); if so, return market_price (join the ask
    exactly, guaranteeing a fill without paying more than necessary).
    For side='sell': symmetric, opportunity when
    market_price >= fair_value + threshold; return market_price.

    Raises ValueError if side is not 'buy' or 'sell', or if threshold < 0.
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if threshold < 0:
        raise ValueError("threshold must not be negative")

    if side == "buy":
        if market_price <= fair_value - threshold:
            return market_price
        return None

    if market_price >= fair_value + threshold:
        return market_price
    return None


def quote_one_tick_better(best_bid: int, best_ask: int, side: str, *, tick: int = 1) -> int:
    """Price one `tick` inside the current best quote on `side`, to
    queue-jump resting orders for a passive (non-crossing) fill.

    For side='buy': candidate = best_bid + tick. If candidate >= best_ask
    (improving would cross or lock the book), fall back to
    best_ask - tick instead. Then clamp the result to be no worse than
    best_bid (max(result, best_bid)) -- i.e. if even the fallback retreats
    below the current best bid, just join the best bid instead of
    quoting worse than the existing market.
    For side='sell': symmetric -- candidate = best_ask - tick, fall back
    to best_bid + tick if candidate <= best_bid, then clamp to
    min(result, best_ask).

    Raises ValueError if best_bid >= best_ask (crossed/locked book,
    malformed input), if side is not 'buy'/'sell', or if tick <= 0.
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if best_bid >= best_ask:
        raise ValueError(f"crossed or locked book: best_bid={best_bid} >= best_ask={best_ask}")
    if tick <= 0:
        raise ValueError("tick must be positive")

    if side == "buy":
        candidate = best_bid + tick
        if candidate >= best_ask:
            candidate = best_ask - tick
        return max(candidate, best_bid)

    candidate = best_ask - tick
    if candidate <= best_bid:
        candidate = best_bid + tick
    return min(candidate, best_ask)


# --- src/p4alpha/core/fair_value.py ---
def naive_mid(bids: dict[int, int], asks: dict[int, int]) -> float | None:
    if not bids or not asks:
        return None
    best_bid = max(bids)
    best_ask = min(asks)
    return (best_bid + best_ask) / 2


def _outer_price(levels: dict[int, int], *, prefer_max_price: bool) -> int:
    max_volume = max(levels.values())
    tied = [price for price, volume in levels.items() if volume == max_volume]
    return max(tied) if prefer_max_price else min(tied)


def outer_anchor(bids: dict[int, int], asks: dict[int, int]) -> float | None:
    if not bids or not asks:
        return None
    bid_price = _outer_price(bids, prefer_max_price=True)
    ask_price = _outer_price(asks, prefer_max_price=False)
    return (bid_price + ask_price) / 2


def two_layer_fair_value(
    bids: dict[int, int],
    asks: dict[int, int],
    *,
    max_inner_deviation: float,
) -> float | None:
    anchor = outer_anchor(bids, asks)
    if anchor is None:
        return None
    inner = naive_mid(bids, asks)
    if inner is not None and abs(inner - anchor) <= max_inner_deviation:
        return (anchor + inner) / 2
    return anchor


# --- src/p4alpha/core/indicators.py ---
from collections import deque
from collections.abc import Sequence
from math import sqrt


class EMA:
    """Exponential moving average, O(1) per update, with an optional pre-feed
    warm start (successive updates over historical values before live use).
    """

    def __init__(self, span: float, pre_feed: Sequence[float] = ()) -> None:
        if span <= 1:
            raise ValueError("span must be > 1")
        self._alpha = 2.0 / (span + 1.0)
        self._value: float | None = None
        for v in pre_feed:
            self.update(v)

    def update(self, value: float) -> float:
        if self._value is None:
            self._value = value
        else:
            self._value += self._alpha * (value - self._value)
        return self._value

    @property
    def value(self) -> float | None:
        return self._value


class RollingMeanStd:
    """Fixed-window rolling mean/std (population std), O(1) per update via a
    running sum and sum-of-squares alongside a bounded deque of raw values.
    """

    def __init__(self, window: int) -> None:
        if window < 2:
            raise ValueError("window must be >= 2")
        self._window = window
        self._values: deque[float] = deque(maxlen=window)
        self._sum = 0.0
        self._sum_sq = 0.0

    def update(self, value: float) -> None:
        if len(self._values) == self._window:
            departing = self._values[0]
            self._sum -= departing
            self._sum_sq -= departing * departing
        self._values.append(value)
        self._sum += value
        self._sum_sq += value * value

    @property
    def ready(self) -> bool:
        return len(self._values) == self._window

    @property
    def mean(self) -> float | None:
        if not self._values:
            return None
        return self._sum / len(self._values)

    @property
    def std(self) -> float | None:
        n = len(self._values)
        if n < 2:
            return None
        mean = self._sum / n
        variance = max(0.0, self._sum_sq / n - mean * mean)
        return sqrt(variance)


class ZScore:
    """Rolling z-score built on RollingMeanStd; None until the window is
    full and has non-zero spread.
    """

    def __init__(self, window: int) -> None:
        self._stats = RollingMeanStd(window)

    def update(self, value: float) -> float | None:
        self._stats.update(value)
        std = self._stats.std
        if not self._stats.ready or std is None or std == 0.0:
            return None
        return (value - self._stats.mean) / std


class LagACF:
    """Rolling lag-k autocorrelation over a fixed window of (x[t], x[t-k])
    pairs, O(1) per update via running sums, no rescan of the window.
    """

    def __init__(self, window: int, lag: int) -> None:
        if lag < 1:
            raise ValueError("lag must be >= 1")
        if window < 2:
            raise ValueError("window must be >= 2")
        self._lag = lag
        self._history: deque[float] = deque(maxlen=lag + 1)
        self._pairs: deque[tuple[float, float]] = deque(maxlen=window)
        self._sum_x = 0.0
        self._sum_y = 0.0
        self._sum_xy = 0.0
        self._sum_x2 = 0.0
        self._sum_y2 = 0.0

    def update(self, value: float) -> float | None:
        self._history.append(value)
        if len(self._history) <= self._lag:
            return None

        lagged = self._history[0]

        if len(self._pairs) == self._pairs.maxlen:
            old_x, old_y = self._pairs[0]
            self._sum_x -= old_x
            self._sum_y -= old_y
            self._sum_xy -= old_x * old_y
            self._sum_x2 -= old_x * old_x
            self._sum_y2 -= old_y * old_y

        self._pairs.append((value, lagged))
        self._sum_x += value
        self._sum_y += lagged
        self._sum_xy += value * lagged
        self._sum_x2 += value * value
        self._sum_y2 += lagged * lagged

        n = len(self._pairs)
        if n < 2:
            return None

        mean_x = self._sum_x / n
        mean_y = self._sum_y / n
        cov = self._sum_xy / n - mean_x * mean_y
        var_x = max(0.0, self._sum_x2 / n - mean_x * mean_x)
        var_y = max(0.0, self._sum_y2 / n - mean_y * mean_y)
        denom = sqrt(var_x * var_y)
        if denom == 0.0:
            return None
        return cov / denom


# --- src/p4alpha/strategies/round5.py ---
import json

from datamodel import Order


POSITION_LIMIT = 10

# --- Part 1: PEBBLES basket-sum ETF arbitrage -------------------------------
# docs/results/round5/leadlag.md Part A: confirmed identity, R^2=0.999998.
PEBBLES_MEMBERS: tuple[str, ...] = ("PEBBLES_L", "PEBBLES_M", "PEBBLES_S", "PEBBLES_XL", "PEBBLES_XS")
TARGET_PEBBLES_SUM = 50000.0

# docs/results/round5/backtest.md: p90/p95/p99 of the live deviation
# z-score (window below), calibrated directly against all three real
# round 5 days, reproduce script in backtest.md. Short window: an
# accounting-identity deviation should self-correct fast (ASH/voucher
# precedent), not drift like PACK/FRUIT.
PEBBLES_ZSCORE_WINDOW = 50
PEBBLES_TIERS: list[tuple[float, int]] = [(1.12, 2), (1.55, 4), (4.93, 6)]
PEBBLES_EXTREME_THRESHOLD = 4.93

# --- Part 2: SNACKPACK relative-value pairs ---------------------------------
# docs/results/round5/leadlag.md B.3: greedy non-overlapping match by
# |lag-0 correlation| descending. SNACKPACK_PISTACHIO is left unpaired
# (its own strongest partners are already used by the pairs below) and
# gets GBM_OUTER_PRODUCTS treatment instead.
SNACKPACK_PAIRS: tuple[tuple[str, str], ...] = (
    ("SNACKPACK_RASPBERRY", "SNACKPACK_STRAWBERRY"),
    ("SNACKPACK_CHOCOLATE", "SNACKPACK_VANILLA"),
)

# docs/results/round5/backtest.md: p90/p95/p99 of the live spread
# z-score, pooled across both pairs (their calibrations were nearly
# identical - within 0.01 of each other at every percentile). Window
# matches PACK/FRUIT's near-unit-root reversion scale (comparable
# half-life order of magnitude, leadlag.md B.2), since there is no
# formula fair value here, only a rolling-mean anchor.
SNACKPACK_PAIR_ZSCORE_WINDOW = 1000
SNACKPACK_PAIR_TIERS: list[tuple[float, int]] = [(2.16, 2), (2.47, 4), (3.11, 6)]
SNACKPACK_PAIR_EXTREME_THRESHOLD = 3.11

# --- Part 4: GBM outer quoting ----------------------------------------------
# Every product not covered above: no confirmed basket identity, no
# economically meaningful correlation, near-unit-root with no reliable
# direction (leadlag.md Part B) - an undirected random walk, whose only
# available edge is passively capturing the spread.
GBM_OUTER_PRODUCTS: tuple[str, ...] = (
    "GALAXY_SOUNDS_BLACK_HOLES",
    "GALAXY_SOUNDS_DARK_MATTER",
    "GALAXY_SOUNDS_PLANETARY_RINGS",
    "GALAXY_SOUNDS_SOLAR_FLAMES",
    "GALAXY_SOUNDS_SOLAR_WINDS",
    "MICROCHIP_CIRCLE",
    "MICROCHIP_OVAL",
    "MICROCHIP_RECTANGLE",
    "MICROCHIP_SQUARE",
    "MICROCHIP_TRIANGLE",
    "OXYGEN_SHAKE_CHOCOLATE",
    "OXYGEN_SHAKE_EVENING_BREATH",
    "OXYGEN_SHAKE_GARLIC",
    "OXYGEN_SHAKE_MINT",
    "OXYGEN_SHAKE_MORNING_BREATH",
    "PANEL_1X2",
    "PANEL_1X4",
    "PANEL_2X2",
    "PANEL_2X4",
    "PANEL_4X4",
    "ROBOT_DISHES",
    "ROBOT_IRONING",
    "ROBOT_LAUNDRY",
    "ROBOT_MOPPING",
    "ROBOT_VACUUMING",
    "SLEEP_POD_COTTON",
    "SLEEP_POD_LAMB_WOOL",
    "SLEEP_POD_NYLON",
    "SLEEP_POD_POLYESTER",
    "SLEEP_POD_SUEDE",
    "TRANSLATOR_ASTRO_BLACK",
    "TRANSLATOR_ECLIPSE_CHARCOAL",
    "TRANSLATOR_GRAPHITE_MIST",
    "TRANSLATOR_SPACE_GRAY",
    "TRANSLATOR_VOID_BLUE",
    "UV_VISOR_AMBER",
    "UV_VISOR_MAGENTA",
    "UV_VISOR_ORANGE",
    "UV_VISOR_RED",
    "UV_VISOR_YELLOW",
    "SNACKPACK_PISTACHIO",
)
GBM_QUOTE_SIZE = 3


def _book(state, product: str) -> tuple[dict[int, int], dict[int, int]]:
    depth = state.order_depths.get(product)
    if depth is None:
        return {}, {}
    bids = dict(depth.buy_orders)
    asks = {price: abs(qty) for price, qty in depth.sell_orders.items()}
    return bids, asks


def _pebbles_mids(state) -> dict[str, float] | None:
    mids: dict[str, float] = {}
    for member in PEBBLES_MEMBERS:
        bids, asks = _book(state, member)
        if not bids or not asks:
            return None
        mid = naive_mid(bids, asks)
        if mid is None:
            return None
        mids[member] = mid
    return mids


def _trade_pebbles_member(
    state, trader_data: dict, *, member: str, mids: dict[str, float]
) -> tuple[list[Order], str | None]:
    """member's fair value is TARGET_PEBBLES_SUM minus its four siblings'
    current mids; deviation from that is z-scored against its own
    rolling mean (matching round3 voucher's reversion_mean_iv precedent:
    the take price targets this member's typical recent deviation, not
    an assumption that the deviation is exactly zero).
    """
    bids, asks = _book(state, member)
    if not bids or not asks:
        return [], None

    fair = TARGET_PEBBLES_SUM - sum(mids[m] for m in PEBBLES_MEMBERS if m != member)
    deviation = mids[member] - fair

    history_key = f"pebbles_dev_history_{member}"
    history = trader_data.get(history_key, [])
    stats = RollingMeanStd(PEBBLES_ZSCORE_WINDOW)
    for value in history:
        stats.update(value)
    stats.update(deviation)
    history.append(deviation)
    trader_data[history_key] = history[-PEBBLES_ZSCORE_WINDOW:]

    if not stats.ready or stats.std is None or stats.std == 0.0:
        return [], None

    z = (deviation - stats.mean) / stats.std
    deviation_abs = abs(z)
    side = "sell" if z > 0 else "buy"
    position = state.position.get(member, 0)

    size = position_tier_size(deviation_abs, PEBBLES_TIERS, position=position, limit=POSITION_LIMIT, side=side)
    if size <= 0:
        return [], None

    best_bid = max(bids)
    best_ask = min(asks)
    quantity = size if side == "buy" else -size

    if deviation_abs >= PEBBLES_EXTREME_THRESHOLD:
        reversion_target = fair + stats.mean
        market_price = best_ask if side == "buy" else best_bid
        take_price = threshold_take_price(reversion_target, market_price, side, threshold=0.0)
        if take_price is None:
            return [], None
        return [Order(member, int(round(take_price)), quantity)], "aggressive"

    quote_price = quote_one_tick_better(best_bid, best_ask, side)
    return [Order(member, quote_price, quantity)], "passive"


def _trade_snackpack_pair(
    state, trader_data: dict, *, leg_a: str, leg_b: str
) -> tuple[list[Order], list[Order], str | None]:
    """Spread = mid(leg_a) - mid(leg_b), z-scored against its own rolling
    mean/std (no formula fair value exists for an empirical correlation
    pair). A positive z means the spread is wider than its recent
    typical level (leg_a relatively expensive): sell leg_a, buy leg_b,
    equal quantity on both legs (a symmetric pairs trade), sized by the
    SMALLER of the two legs' available room so the trade never goes out
    unbalanced. An aggressive take requires BOTH legs' edge to clear the
    threshold independently; if only one leg does, neither is sent.
    """
    bids_a, asks_a = _book(state, leg_a)
    bids_b, asks_b = _book(state, leg_b)
    if not bids_a or not asks_a or not bids_b or not asks_b:
        return [], [], None

    mid_a = naive_mid(bids_a, asks_a)
    mid_b = naive_mid(bids_b, asks_b)
    if mid_a is None or mid_b is None:
        return [], [], None

    spread = mid_a - mid_b
    history_key = f"snack_spread_history_{leg_a}_{leg_b}"
    history = trader_data.get(history_key, [])
    stats = RollingMeanStd(SNACKPACK_PAIR_ZSCORE_WINDOW)
    for value in history:
        stats.update(value)
    stats.update(spread)
    history.append(spread)
    trader_data[history_key] = history[-SNACKPACK_PAIR_ZSCORE_WINDOW:]

    if not stats.ready or stats.std is None or stats.std == 0.0:
        return [], [], None

    z = (spread - stats.mean) / stats.std
    deviation_abs = abs(z)
    side_a = "sell" if z > 0 else "buy"
    side_b = "buy" if z > 0 else "sell"

    position_a = state.position.get(leg_a, 0)
    position_b = state.position.get(leg_b, 0)
    size_a = position_tier_size(
        deviation_abs, SNACKPACK_PAIR_TIERS, position=position_a, limit=POSITION_LIMIT, side=side_a
    )
    size_b = position_tier_size(
        deviation_abs, SNACKPACK_PAIR_TIERS, position=position_b, limit=POSITION_LIMIT, side=side_b
    )
    size = min(size_a, size_b)
    if size <= 0:
        return [], [], None

    best_bid_a, best_ask_a = max(bids_a), min(asks_a)
    best_bid_b, best_ask_b = max(bids_b), min(asks_b)
    quantity_a = size if side_a == "buy" else -size
    quantity_b = size if side_b == "buy" else -size

    if deviation_abs >= SNACKPACK_PAIR_EXTREME_THRESHOLD:
        fair_a = mid_b + stats.mean
        fair_b = mid_a - stats.mean
        market_price_a = best_ask_a if side_a == "buy" else best_bid_a
        market_price_b = best_ask_b if side_b == "buy" else best_bid_b
        take_price_a = threshold_take_price(fair_a, market_price_a, side_a, threshold=0.0)
        take_price_b = threshold_take_price(fair_b, market_price_b, side_b, threshold=0.0)
        if take_price_a is None or take_price_b is None:
            return [], [], None
        return (
            [Order(leg_a, int(round(take_price_a)), quantity_a)],
            [Order(leg_b, int(round(take_price_b)), quantity_b)],
            "aggressive",
        )

    quote_price_a = quote_one_tick_better(best_bid_a, best_ask_a, side_a)
    quote_price_b = quote_one_tick_better(best_bid_b, best_ask_b, side_b)
    return (
        [Order(leg_a, quote_price_a, quantity_a)],
        [Order(leg_b, quote_price_b, quantity_b)],
        "passive",
    )


def _quote_outer(state, *, product: str) -> list[Order]:
    """Two-sided passive market-making, no directional or reversion view
    (module docstring, part 4): size throttles toward zero as position
    approaches either side of the limit, so this never needs to breach
    it or check afterward.
    """
    bids, asks = _book(state, product)
    if not bids or not asks:
        return []
    best_bid = max(bids)
    best_ask = min(asks)
    if best_bid >= best_ask:
        return []

    position = state.position.get(product, 0)
    orders: list[Order] = []

    buy_size = min(GBM_QUOTE_SIZE, max(0, POSITION_LIMIT - position))
    if buy_size > 0:
        orders.append(Order(product, quote_one_tick_better(best_bid, best_ask, "buy"), buy_size))

    sell_size = min(GBM_QUOTE_SIZE, max(0, position + POSITION_LIMIT))
    if sell_size > 0:
        orders.append(Order(product, quote_one_tick_better(best_bid, best_ask, "sell"), -sell_size))

    return orders


class Trader:
    """enable_pebbles_arbitrage defaults to False (module docstring: a
    direct counterfactual measurement found the arbitrage WORSE than
    GBM-outer quoting on every one of the three backtest days, not
    merely a weak edge). `prosperity4bt`'s CLI always instantiates
    Trader() with no arguments, so the shipped/competition default routes
    PEBBLES_MEMBERS through `_quote_outer` instead; passing
    enable_pebbles_arbitrage=True is for research reproduction only
    (docs/results/round5/backtest.md, tests/strategies/test_round5.py).
    """

    def __init__(self, enable_pebbles_arbitrage: bool = False):
        self.enable_pebbles_arbitrage = enable_pebbles_arbitrage

    def run(self, state):
        trader_data = json.loads(state.traderData) if state.traderData else {}
        orders: dict[str, list[Order]] = {}

        if self.enable_pebbles_arbitrage:
            pebbles_mids = _pebbles_mids(state)
            if pebbles_mids is not None:
                for member in PEBBLES_MEMBERS:
                    member_orders, _ = _trade_pebbles_member(state, trader_data, member=member, mids=pebbles_mids)
                    if member_orders:
                        orders[member] = member_orders

        for leg_a, leg_b in SNACKPACK_PAIRS:
            orders_a, orders_b, _ = _trade_snackpack_pair(state, trader_data, leg_a=leg_a, leg_b=leg_b)
            if orders_a:
                orders[leg_a] = orders_a
            if orders_b:
                orders[leg_b] = orders_b

        outer_products = GBM_OUTER_PRODUCTS if self.enable_pebbles_arbitrage else GBM_OUTER_PRODUCTS + PEBBLES_MEMBERS
        for product in outer_products:
            outer_orders = _quote_outer(state, product=product)
            if outer_orders:
                orders[product] = outer_orders

        return orders, 0, json.dumps(trader_data)
