# Generated by p4alpha.flatten.flatten -- DO NOT EDIT BY HAND.
# Source: src/p4alpha/core/execution.py, core/fair_value.py, core/indicators.py, core/options.py + src/p4alpha/strategies/round3.py.
# Regenerate with: python -m p4alpha.flatten.flatten
# Competition-legal single file: stdlib only, plus the runtime-injected
# `datamodel` module (PLAN.md §7). Default construction (Trader())
# is the only path prosperity4bt's CLI ever calls; any opt-in
# constructor flag below is dead on that path by design.

from __future__ import annotations

# --- src/p4alpha/core/execution.py ---
from collections.abc import Sequence

_SIDES = ("buy", "sell")


def position_tier_size(
    deviation: float,
    tiers: Sequence[tuple[float, int]],
    *,
    position: int,
    limit: int,
    side: str,
) -> int:
    """Order size for a signal of magnitude `deviation` (e.g. an absolute
    z-score), given a caller-supplied, strictly-ascending-by-threshold
    list of (deviation_threshold, order_size) tiers: use the order_size
    of the highest threshold not exceeding `deviation` (0 if `deviation`
    is below every tier's threshold). The chosen size is then clamped to
    respect the position limit: for side='buy', capped at
    max(0, limit - position); for side='sell', capped at
    max(0, position + limit). Returns a non-negative quantity; the
    caller applies the sign for a sell order.

    Raises ValueError if:
    - side is not 'buy' or 'sell'
    - tiers is empty
    - tiers is not strictly ascending by threshold (tiers[i][0] must be >
      tiers[i-1][0] for all i > 0)
    - any tier's order_size is negative
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if not tiers:
        raise ValueError("tiers must not be empty")

    size = 0
    previous_threshold = None
    for threshold, order_size in tiers:
        if previous_threshold is not None and threshold <= previous_threshold:
            raise ValueError("tiers must be strictly ascending by threshold")
        if order_size < 0:
            raise ValueError("tier order_size must not be negative")
        previous_threshold = threshold
        if deviation >= threshold:
            size = order_size

    if side == "buy":
        room = max(0, limit - position)
    else:
        room = max(0, position + limit)
    return min(size, room)


def exposure_capped_size(
    candidate_quantity: int,
    *,
    current_exposure: float,
    cap: float,
) -> int:
    """Clamp a candidate signed order quantity so current_exposure plus its
    contribution never pushes an aggregate exposure figure beyond +-cap, in
    whichever direction candidate_quantity moves it (positive grows
    exposure, negative shrinks it). Generalises position_tier_size's own
    limit clamp from a caller's single integer position to an externally
    computed float exposure (e.g. a portfolio's net delta to a correlated
    underlying, stacked across several instruments a single instrument's
    own position limit cannot bound; added in Stage 5, STATE.md decisions
    log, for strategies/round3.py's correlation-stacking exposure cap).

    Returns 0 if current_exposure already meets or exceeds the cap in the
    same direction as candidate_quantity. Preserves candidate_quantity's
    sign; magnitude only ever shrinks, never grows. Room is truncated
    toward zero (int()) rather than rounded, since exposure is a
    fractional delta-weighted figure but order quantity is integral, and
    truncating is the direction that never lets the cap be exceeded.

    Raises ValueError if cap <= 0.
    """
    if cap <= 0:
        raise ValueError(f"cap must be > 0, got {cap}")

    if candidate_quantity > 0:
        room = max(0.0, cap - current_exposure)
        return min(candidate_quantity, int(room))
    if candidate_quantity < 0:
        room = max(0.0, cap + current_exposure)
        return -min(-candidate_quantity, int(room))
    return 0


def threshold_take_price(
    fair_value: float,
    market_price: float,
    side: str,
    threshold: float,
) -> float | None:
    """The price to send a marketable (spread-crossing) order at, when
    `market_price` (the *opposing* side's best quote: the best ask when
    side='buy', the best bid when side='sell') is mispriced against
    `fair_value` by more than `threshold`. Returns None when the edge
    does not clear the threshold (no order should be sent).

    For side='buy': the opportunity exists when
    market_price <= fair_value - threshold (the ask is cheap enough
    relative to fair value); if so, return market_price (join the ask
    exactly, guaranteeing a fill without paying more than necessary).
    For side='sell': symmetric, opportunity when
    market_price >= fair_value + threshold; return market_price.

    Raises ValueError if side is not 'buy' or 'sell', or if threshold < 0.
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if threshold < 0:
        raise ValueError("threshold must not be negative")

    if side == "buy":
        if market_price <= fair_value - threshold:
            return market_price
        return None

    if market_price >= fair_value + threshold:
        return market_price
    return None


def quote_one_tick_better(best_bid: int, best_ask: int, side: str, *, tick: int = 1) -> int:
    """Price one `tick` inside the current best quote on `side`, to
    queue-jump resting orders for a passive (non-crossing) fill.

    For side='buy': candidate = best_bid + tick. If candidate >= best_ask
    (improving would cross or lock the book), fall back to
    best_ask - tick instead. Then clamp the result to be no worse than
    best_bid (max(result, best_bid)) -- i.e. if even the fallback retreats
    below the current best bid, just join the best bid instead of
    quoting worse than the existing market.
    For side='sell': symmetric -- candidate = best_ask - tick, fall back
    to best_bid + tick if candidate <= best_bid, then clamp to
    min(result, best_ask).

    Raises ValueError if best_bid >= best_ask (crossed/locked book,
    malformed input), if side is not 'buy'/'sell', or if tick <= 0.
    """
    if side not in _SIDES:
        raise ValueError(f"side must be 'buy' or 'sell', got {side!r}")
    if best_bid >= best_ask:
        raise ValueError(f"crossed or locked book: best_bid={best_bid} >= best_ask={best_ask}")
    if tick <= 0:
        raise ValueError("tick must be positive")

    if side == "buy":
        candidate = best_bid + tick
        if candidate >= best_ask:
            candidate = best_ask - tick
        return max(candidate, best_bid)

    candidate = best_ask - tick
    if candidate <= best_bid:
        candidate = best_bid + tick
    return min(candidate, best_ask)


# --- src/p4alpha/core/fair_value.py ---
def naive_mid(bids: dict[int, int], asks: dict[int, int]) -> float | None:
    if not bids or not asks:
        return None
    best_bid = max(bids)
    best_ask = min(asks)
    return (best_bid + best_ask) / 2


def _outer_price(levels: dict[int, int], *, prefer_max_price: bool) -> int:
    max_volume = max(levels.values())
    tied = [price for price, volume in levels.items() if volume == max_volume]
    return max(tied) if prefer_max_price else min(tied)


def outer_anchor(bids: dict[int, int], asks: dict[int, int]) -> float | None:
    if not bids or not asks:
        return None
    bid_price = _outer_price(bids, prefer_max_price=True)
    ask_price = _outer_price(asks, prefer_max_price=False)
    return (bid_price + ask_price) / 2


def two_layer_fair_value(
    bids: dict[int, int],
    asks: dict[int, int],
    *,
    max_inner_deviation: float,
) -> float | None:
    anchor = outer_anchor(bids, asks)
    if anchor is None:
        return None
    inner = naive_mid(bids, asks)
    if inner is not None and abs(inner - anchor) <= max_inner_deviation:
        return (anchor + inner) / 2
    return anchor


# --- src/p4alpha/core/indicators.py ---
from collections import deque
from collections.abc import Sequence
from math import sqrt


class EMA:
    """Exponential moving average, O(1) per update, with an optional pre-feed
    warm start (successive updates over historical values before live use).
    """

    def __init__(self, span: float, pre_feed: Sequence[float] = ()) -> None:
        if span <= 1:
            raise ValueError("span must be > 1")
        self._alpha = 2.0 / (span + 1.0)
        self._value: float | None = None
        for v in pre_feed:
            self.update(v)

    def update(self, value: float) -> float:
        if self._value is None:
            self._value = value
        else:
            self._value += self._alpha * (value - self._value)
        return self._value

    @property
    def value(self) -> float | None:
        return self._value


class RollingMeanStd:
    """Fixed-window rolling mean/std (population std), O(1) per update via a
    running sum and sum-of-squares alongside a bounded deque of raw values.
    """

    def __init__(self, window: int) -> None:
        if window < 2:
            raise ValueError("window must be >= 2")
        self._window = window
        self._values: deque[float] = deque(maxlen=window)
        self._sum = 0.0
        self._sum_sq = 0.0

    def update(self, value: float) -> None:
        if len(self._values) == self._window:
            departing = self._values[0]
            self._sum -= departing
            self._sum_sq -= departing * departing
        self._values.append(value)
        self._sum += value
        self._sum_sq += value * value

    @property
    def ready(self) -> bool:
        return len(self._values) == self._window

    @property
    def mean(self) -> float | None:
        if not self._values:
            return None
        return self._sum / len(self._values)

    @property
    def std(self) -> float | None:
        n = len(self._values)
        if n < 2:
            return None
        mean = self._sum / n
        variance = max(0.0, self._sum_sq / n - mean * mean)
        return sqrt(variance)


class ZScore:
    """Rolling z-score built on RollingMeanStd; None until the window is
    full and has non-zero spread.
    """

    def __init__(self, window: int) -> None:
        self._stats = RollingMeanStd(window)

    def update(self, value: float) -> float | None:
        self._stats.update(value)
        std = self._stats.std
        if not self._stats.ready or std is None or std == 0.0:
            return None
        return (value - self._stats.mean) / std


class LagACF:
    """Rolling lag-k autocorrelation over a fixed window of (x[t], x[t-k])
    pairs, O(1) per update via running sums, no rescan of the window.
    """

    def __init__(self, window: int, lag: int) -> None:
        if lag < 1:
            raise ValueError("lag must be >= 1")
        if window < 2:
            raise ValueError("window must be >= 2")
        self._lag = lag
        self._history: deque[float] = deque(maxlen=lag + 1)
        self._pairs: deque[tuple[float, float]] = deque(maxlen=window)
        self._sum_x = 0.0
        self._sum_y = 0.0
        self._sum_xy = 0.0
        self._sum_x2 = 0.0
        self._sum_y2 = 0.0

    def update(self, value: float) -> float | None:
        self._history.append(value)
        if len(self._history) <= self._lag:
            return None

        lagged = self._history[0]

        if len(self._pairs) == self._pairs.maxlen:
            old_x, old_y = self._pairs[0]
            self._sum_x -= old_x
            self._sum_y -= old_y
            self._sum_xy -= old_x * old_y
            self._sum_x2 -= old_x * old_x
            self._sum_y2 -= old_y * old_y

        self._pairs.append((value, lagged))
        self._sum_x += value
        self._sum_y += lagged
        self._sum_xy += value * lagged
        self._sum_x2 += value * value
        self._sum_y2 += lagged * lagged

        n = len(self._pairs)
        if n < 2:
            return None

        mean_x = self._sum_x / n
        mean_y = self._sum_y / n
        cov = self._sum_xy / n - mean_x * mean_y
        var_x = max(0.0, self._sum_x2 / n - mean_x * mean_x)
        var_y = max(0.0, self._sum_y2 / n - mean_y * mean_y)
        denom = sqrt(var_x * var_y)
        if denom == 0.0:
            return None
        return cov / denom


# --- src/p4alpha/core/options.py ---
import math

_ERF_P = 0.3275911
_ERF_A1 = 0.254829592
_ERF_A2 = -0.284496736
_ERF_A3 = 1.421413741
_ERF_A4 = -1.453152027
_ERF_A5 = 1.061405429


def _erf(t: float) -> float:
    """Abramowitz-Stegun 7.1.26 rational approximation of erf(t), t >= 0."""
    u = 1.0 / (1.0 + _ERF_P * t)
    poly = ((((_ERF_A5 * u + _ERF_A4) * u + _ERF_A3) * u + _ERF_A2) * u + _ERF_A1) * u
    return 1.0 - poly * math.exp(-t * t)


def norm_cdf(x: float) -> float:
    """Standard normal CDF via the Abramowitz-Stegun 7.1.26 rational
    approximation of erf. Max absolute error 7.5e-8 for all real x.
    """
    if x >= 0:
        return 0.5 * (1.0 + _erf(x / math.sqrt(2.0)))
    return 1.0 - norm_cdf(-x)


def black_scholes_call(
    spot: float, strike: float, time_to_expiry: float, vol: float, rate: float = 0.0
) -> float:
    """European call price. Raises ValueError if spot <= 0, strike <= 0,
    time_to_expiry <= 0, or vol <= 0.
    """
    if spot <= 0:
        raise ValueError(f"spot must be > 0, got {spot}")
    if strike <= 0:
        raise ValueError(f"strike must be > 0, got {strike}")
    if time_to_expiry <= 0:
        raise ValueError(f"time_to_expiry must be > 0, got {time_to_expiry}")
    if vol <= 0:
        raise ValueError(f"vol must be > 0, got {vol}")

    sqrt_t = math.sqrt(time_to_expiry)
    d1 = (math.log(spot / strike) + (rate + 0.5 * vol * vol) * time_to_expiry) / (vol * sqrt_t)
    d2 = d1 - vol * sqrt_t
    return spot * norm_cdf(d1) - strike * math.exp(-rate * time_to_expiry) * norm_cdf(d2)


def black_scholes_call_delta(
    spot: float, strike: float, time_to_expiry: float, vol: float, rate: float = 0.0
) -> float:
    """European call delta, dPrice/dSpot = N(d1) exactly (the S*N(d1) and
    -K*exp(-rT)*N(d2) terms' spot-derivatives cancel in the standard
    derivation, leaving just N(d1)); no separate closed form needed beyond
    norm_cdf. Raises the same ValueErrors as black_scholes_call for the
    same invalid inputs, since d1 is undefined otherwise.
    """
    if spot <= 0:
        raise ValueError(f"spot must be > 0, got {spot}")
    if strike <= 0:
        raise ValueError(f"strike must be > 0, got {strike}")
    if time_to_expiry <= 0:
        raise ValueError(f"time_to_expiry must be > 0, got {time_to_expiry}")
    if vol <= 0:
        raise ValueError(f"vol must be > 0, got {vol}")

    sqrt_t = math.sqrt(time_to_expiry)
    d1 = (math.log(spot / strike) + (rate + 0.5 * vol * vol) * time_to_expiry) / (vol * sqrt_t)
    return norm_cdf(d1)


def implied_vol_call(
    price: float,
    spot: float,
    strike: float,
    time_to_expiry: float,
    rate: float = 0.0,
    *,
    lo: float = 1e-6,
    hi: float = 5.0,
    tol: float = 1e-6,
    max_iter: int = 100,
) -> float:
    """Bisection search for the vol that reprices `price` via
    black_scholes_call. Raises ValueError if time_to_expiry <= 0, or if
    `price` cannot be bracketed within [lo, hi] vol (i.e.
    black_scholes_call(..., lo, ...) > price, meaning even near-zero vol
    overprices it, likely a stale/bad quote, or
    black_scholes_call(..., hi, ...) < price, meaning even 500% vol
    can't reach it). Standard bisection loop, up to max_iter iterations
    or until the bracket width is below tol, whichever first.
    """
    if time_to_expiry <= 0:
        raise ValueError(f"time_to_expiry must be > 0, got {time_to_expiry}")

    price_lo = black_scholes_call(spot, strike, time_to_expiry, lo, rate)
    price_hi = black_scholes_call(spot, strike, time_to_expiry, hi, rate)

    if price_lo > price:
        raise ValueError(
            f"price {price} is below what lo vol {lo} produces ({price_lo}); "
            "cannot bracket, likely a stale/bad quote"
        )
    if price_hi < price:
        raise ValueError(
            f"price {price} is above what hi vol {hi} produces ({price_hi}); cannot bracket"
        )

    for _ in range(max_iter):
        if hi - lo < tol:
            break
        mid = 0.5 * (lo + hi)
        price_mid = black_scholes_call(spot, strike, time_to_expiry, mid, rate)
        if price_mid < price:
            lo = mid
        else:
            hi = mid

    return 0.5 * (lo + hi)


# --- src/p4alpha/strategies/round3.py ---
import json

from datamodel import Order


PACK = "HYDROGEL_PACK"
FRUIT = "VELVETFRUIT_EXTRACT"
VOUCHER_PREFIX = "VEV_"

# Confirmed absent from prosperity4bt.data.LIMITS (round-5-only entries),
# so PACK, FRUIT and every voucher fall through to DEFAULT_POSITION_LIMIT
# = 50, the same fact already established for round 1/2 (STATE.md
# decisions log, 2026-07-18).
POSITION_LIMIT = 50

# docs/results/round3/optionsurface.md section 5: level-1 spread (price
# units), pooled across all three days. Liquid strikes clear a
# single-instrument reversion edge without crossing the spread (section
# 6 breakeven_z 1.25-3.49); illiquid strikes need a much larger deviation
# (breakeven_z 3.19-11.11) to clear it even once, so they trade only via
# a thresholded take, never a passive quote.
LIQUID_VOUCHER_STRIKES: tuple[int, ...] = (5300, 5400, 5500)
ILLIQUID_VOUCHER_STRIKES: tuple[int, ...] = (5000, 5100, 5200)
ACTIVE_VOUCHER_STRIKES: tuple[int, ...] = LIQUID_VOUCHER_STRIKES + ILLIQUID_VOUCHER_STRIKES

# Calibrated 2026-07-18 against the real pinned package data via
# research.regime.zscore_tier_calibration (PACK/FRUIT, window=1000,
# pooled across round 3's three days) and an equivalent pooled implied-
# vol z-score calibration over ACTIVE_VOUCHER_STRIKES (window=50); see
# docs/results/round3/backtest.md "Parameter calibration" for the exact
# reproduction. PACK: p90=2.04, p95=2.36, p99=2.99 (n=27003, both
# products pooled together in that run; FRUIT's own column is listed
# separately below). FRUIT: p90=2.18, p95=2.50, p99=3.01. Vouchers
# (pooled across all six active strikes, n=179115): p90=1.65, p95=2.12,
# p99=3.17.
#
# PACK_ZSCORE_WINDOW/FRUIT_ZSCORE_WINDOW = 1000: docs/results/round3/
# regime.md measures PACK/FRUIT half-lives at 189-420 ticks, two orders
# of magnitude past ASH's 1.6-2.9 (round 1), which used a 17-31x-half-
# life window (50). The same ratio here would need a 3000-13000-tick
# window; traderData does not persist across days (see module docstring)
# and a single day is only 10000 ticks, so window=1000 (roughly 2.4-5.3x
# the measured half-lives) is the largest window that can plausibly
# refill several times within one day, a deliberate, documented
# departure from ASH's ratio forced by the tick budget, not a re-
# derivation of what "should" be optimal.
PACK_ZSCORE_WINDOW = 1000
PACK_TIERS: list[tuple[float, int]] = [(2.04, 5), (2.36, 10), (2.99, 15)]
PACK_EXTREME_THRESHOLD = 2.99
FRUIT_ZSCORE_WINDOW = 1000
FRUIT_TIERS: list[tuple[float, int]] = [(2.18, 5), (2.50, 10), (3.01, 15)]
FRUIT_EXTREME_THRESHOLD = 3.01

# PACK/FRUIT tier sizes (5/10/15, versus ASH's 10/25/50 at a comparable
# shape) are deliberately capped well below POSITION_LIMIT: docs/results/
# round3/regime.md characterises both as near-unit-root (phi 0.996-
# 0.998), "barely distinguishable from a pure random walk within a
# single day's data", a materially weaker and less robust signal than
# ASH's; sizing at ASH's scale would overstate confidence the research
# does not support. This is a strategy risk-sizing judgement, not a
# re-reading of the calibrated thresholds above, which are the real
# measured percentiles.

# Vouchers: half-life 0.2-31 ticks (docs/results/round3/optionsurface.md
# section 4) is genuinely fast, matching the confidence ASH's own tiers
# were built on, so the full POSITION_LIMIT is used at the extreme tier.
# ILLIQUID_VOUCHER_TIERS' one entry sits exactly at VOUCHER_EXTREME_THRESHOLD
# by construction: illiquid strikes get no tier below it, so
# position_tier_size can only ever return a non-zero size for them when
# deviation >= VOUCHER_EXTREME_THRESHOLD, which _trade_voucher's own
# extreme-tier branch always catches first. That is the entire mechanism
# behind "thresholded takes elsewhere" (PLAN.md) for illiquid strikes; no
# separate liquid/illiquid branch is needed in _trade_voucher itself.
VOUCHER_ZSCORE_WINDOW = 50
LIQUID_VOUCHER_TIERS: list[tuple[float, int]] = [(1.65, 10), (2.12, 25), (3.17, 50)]
ILLIQUID_VOUCHER_TIERS: list[tuple[float, int]] = [(3.17, 50)]
VOUCHER_EXTREME_THRESHOLD = 3.17

# docs/results/round3/optionsurface.md section 1: voucher expiry
# calibrated at day D=8.25 (expires at timestamp 0 of day D). See module
# docstring for why a live Trader.run() must assume a fixed day rather
# than reading the true one.
VOUCHER_EXPIRY_DAY = 8.25
ASSUMED_DAY = 1
TICKS_PER_DAY = 1_000_000

# 2x POSITION_LIMIT: a single instrument's own +-50 limit already bounds
# its individual risk; this caps the *additional* directional risk from
# several FRUIT-linked instruments moving together, at a multiple large
# enough to still allow genuine diversification benefit (not simply
# refusing any simultaneous exposure) while bounding the worst case
# measured and reported in docs/results/round3/backtest.md. Units:
# delta-weighted share-equivalents (FRUIT shares, or vouchers shares
# scaled by their own current Black-Scholes delta), the same units
# `_current_voucher_deltas`/`_cap_voucher_exposure` compute in.
CORRELATION_EXPOSURE_CAP = 2.0 * POSITION_LIMIT

# Reduce-only skew size when already over the cap (module docstring has
# the full test-vs-adopt comparison): small relative to a full tier size
# (10-50), a passive nudge rather than an attempt to fully close the
# position in one tick.
REDUCE_ONLY_SKEW_SIZE = 5


def _book(state, product: str) -> tuple[dict[int, int], dict[int, int]]:
    depth = state.order_depths.get(product)
    if depth is None:
        return {}, {}
    bids = dict(depth.buy_orders)
    asks = {price: abs(qty) for price, qty in depth.sell_orders.items()}
    return bids, asks


def _voucher_time_to_expiry(timestamp: int) -> float:
    return VOUCHER_EXPIRY_DAY - ASSUMED_DAY - timestamp / TICKS_PER_DAY


def _trade_reverting_instrument(
    state,
    trader_data: dict,
    *,
    product: str,
    history_key: str,
    window: int,
    tiers: list[tuple[float, int]],
    extreme_threshold: float,
) -> tuple[list[Order], str | None]:
    """Shared PACK/FRUIT logic: rolling mean/std of raw mid_price drives a
    z-score; position_tier_size sizes the trade; the extreme tier crosses
    the spread (threshold_take_price, confirmed against the rolling mean
    as fair value), anything below it quotes passively one tick better.

    Returns (orders, mechanism): mechanism is "aggressive" for a
    threshold-take, "passive" for a quote, None when no order was sent.
    Exposed to the caller (rather than left implicit) so per-mechanism
    PnL attribution (docs/results/round3/backtest.md) can be computed
    from the strategy's own actual branch decision, not inferred after
    the fact from order prices.
    """
    bids, asks = _book(state, product)
    if not bids or not asks:
        return [], None

    mid = naive_mid(bids, asks)
    if mid is None:
        return [], None

    history = trader_data.get(history_key, [])
    stats = RollingMeanStd(window)
    for value in history:
        stats.update(value)
    stats.update(mid)

    history.append(mid)
    trader_data[history_key] = history[-window:]

    if not stats.ready or stats.std is None or stats.std == 0.0:
        return [], None

    reversion_mean = stats.mean
    z = (mid - reversion_mean) / stats.std
    deviation = abs(z)
    side = "sell" if z > 0 else "buy"
    position = state.position.get(product, 0)

    size = position_tier_size(deviation, tiers, position=position, limit=POSITION_LIMIT, side=side)
    if size <= 0:
        return [], None

    best_bid = max(bids)
    best_ask = min(asks)
    quantity = size if side == "buy" else -size

    if deviation >= extreme_threshold:
        market_price = best_ask if side == "buy" else best_bid
        take_price = threshold_take_price(reversion_mean, market_price, side, threshold=0.0)
        if take_price is None:
            return [], None
        return [Order(product, int(round(take_price)), quantity)], "aggressive"

    quote_price = quote_one_tick_better(best_bid, best_ask, side)
    return [Order(product, quote_price, quantity)], "passive"


def _voucher_iv(fruit_mid: float, voucher_mid: float, strike: int, tte: float) -> float | None:
    try:
        return implied_vol_call(voucher_mid, fruit_mid, strike, tte)
    except ValueError:
        # Unbracketable quote (near-intrinsic deep-ITM-style pricing on a
        # coarse grid): docs/results/round3/optionsurface.md section 3
        # found this essentially never happens on the six active strikes
        # (0 skips across all three days), unlike the four excluded ones;
        # treated as "no signal this tick", matching _book's own
        # empty-book handling, not a data error to raise on.
        return None


def _current_voucher_deltas(state, fruit_mid: float, tte: float) -> dict[int, float]:
    """Best-effort current delta for every active voucher, from this
    tick's own market mid (not the rolling-mean vol): the exposure cap
    below needs each voucher's *current* directional sensitivity, not
    the vol level the reversion signal targets. A voucher with no usable
    quote this tick contributes no entry (treated as zero exposure for
    this tick's snapshot only; its actual position is unaffected).
    """
    deltas: dict[int, float] = {}
    for strike in ACTIVE_VOUCHER_STRIKES:
        bids, asks = _book(state, f"{VOUCHER_PREFIX}{strike}")
        mid = naive_mid(bids, asks)
        if mid is None:
            continue
        iv = _voucher_iv(fruit_mid, mid, strike, tte)
        if iv is None:
            continue
        deltas[strike] = black_scholes_call_delta(fruit_mid, strike, tte, iv)
    return deltas


def _cap_voucher_exposure(quantity: int, *, delta: float, running_exposure: float) -> int:
    """Clamp a candidate voucher order so running_exposure plus its delta-
    weighted contribution never exceeds +-CORRELATION_EXPOSURE_CAP. One
    voucher share moves FRUIT-equivalent exposure by `delta` (a fraction
    in (0, 1)), not 1:1 like a direct FRUIT/PACK position, so this is not
    core.execution.exposure_capped_size's simple 1:1 case; delta-scaling
    is specific to an option's exposure and kept local to this strategy
    rather than generalising the shared core/ primitive for one call site.
    """
    if quantity == 0 or delta <= 0:
        return 0
    if quantity > 0:
        room = max(0.0, CORRELATION_EXPOSURE_CAP - running_exposure)
    else:
        room = max(0.0, CORRELATION_EXPOSURE_CAP + running_exposure)
    capped = min(abs(quantity), int(room / delta))
    return capped if quantity > 0 else -capped


def _trade_voucher(
    state,
    trader_data: dict,
    *,
    strike: int,
    fruit_mid: float,
    tte: float,
    tiers: list[tuple[float, int]],
    running_exposure: float,
) -> tuple[list[Order], float, str | None]:
    """One voucher's reversion decision. Returns (orders, exposure_delta,
    mechanism): exposure_delta is this voucher's own current delta times
    whatever quantity was actually sent (0.0 if nothing was sent), for
    the caller to fold into the running exposure total before processing
    the next voucher in the same tick; mechanism is "aggressive" for a
    threshold-take, "passive" for a quote, None when no order was sent
    (exposed for per-mechanism PnL attribution, same reasoning as
    _trade_reverting_instrument above).
    """
    product = f"{VOUCHER_PREFIX}{strike}"
    bids, asks = _book(state, product)
    if not bids or not asks:
        return [], 0.0, None

    voucher_mid = naive_mid(bids, asks)
    if voucher_mid is None:
        return [], 0.0, None

    current_iv = _voucher_iv(fruit_mid, voucher_mid, strike, tte)
    if current_iv is None:
        return [], 0.0, None

    history_key = f"voucher_iv_history_{strike}"
    history = trader_data.get(history_key, [])
    stats = RollingMeanStd(VOUCHER_ZSCORE_WINDOW)
    for value in history:
        stats.update(value)
    stats.update(current_iv)

    history.append(current_iv)
    trader_data[history_key] = history[-VOUCHER_ZSCORE_WINDOW:]

    if not stats.ready or stats.std is None or stats.std == 0.0:
        return [], 0.0, None

    reversion_mean_iv = stats.mean
    z = (current_iv - reversion_mean_iv) / stats.std
    deviation = abs(z)
    side = "sell" if z > 0 else "buy"
    position = state.position.get(product, 0)

    size = position_tier_size(deviation, tiers, position=position, limit=POSITION_LIMIT, side=side)
    if size <= 0:
        return [], 0.0, None

    quantity = size if side == "buy" else -size
    delta = black_scholes_call_delta(fruit_mid, strike, tte, current_iv)
    quantity = _cap_voucher_exposure(quantity, delta=delta, running_exposure=running_exposure)
    if quantity == 0:
        return [], 0.0, None

    best_bid = max(bids)
    best_ask = min(asks)

    if deviation >= VOUCHER_EXTREME_THRESHOLD:
        fair_price = black_scholes_call(fruit_mid, strike, tte, reversion_mean_iv)
        market_price = best_ask if side == "buy" else best_bid
        take_price = threshold_take_price(fair_price, market_price, side, threshold=0.0)
        if take_price is None:
            return [], 0.0, None
        return [Order(product, int(round(take_price)), quantity)], quantity * delta, "aggressive"

    quote_price = quote_one_tick_better(best_bid, best_ask, side)
    return [Order(product, quote_price, quantity)], quantity * delta, "passive"


def _reduce_only_order(state, *, strike: int, baseline_exposure: float) -> Order | None:
    """Passive reduce-only skew (module docstring has the tested-vs-
    adopted comparison): only fires when the aggregate exposure is
    already at or past the cap and this voucher's own held position
    contributes to that same over-cap direction. Signal-independent by
    design (it does not consult the reversion z-score at all) and small
    relative to a full tier size, since it exists to nudge the book back
    toward the cap over time, not to substitute for the reversion
    signal's own sizing.
    """
    if abs(baseline_exposure) < CORRELATION_EXPOSURE_CAP:
        return None

    product = f"{VOUCHER_PREFIX}{strike}"
    position = state.position.get(product, 0)
    if position == 0 or (position > 0) != (baseline_exposure > 0):
        return None

    bids, asks = _book(state, product)
    if not bids or not asks:
        return None

    close_side = "sell" if position > 0 else "buy"
    size = min(REDUCE_ONLY_SKEW_SIZE, abs(position))
    quote_price = quote_one_tick_better(max(bids), min(asks), close_side)
    quantity = -size if close_side == "sell" else size
    return Order(product, quote_price, quantity)


class Trader:
    def run(self, state):
        trader_data = json.loads(state.traderData) if state.traderData else {}

        orders: dict[str, list[Order]] = {}

        pack_orders, _ = _trade_reverting_instrument(
            state,
            trader_data,
            product=PACK,
            history_key="pack_history",
            window=PACK_ZSCORE_WINDOW,
            tiers=PACK_TIERS,
            extreme_threshold=PACK_EXTREME_THRESHOLD,
        )
        if pack_orders:
            orders[PACK] = pack_orders

        fruit_orders, _ = _trade_reverting_instrument(
            state,
            trader_data,
            product=FRUIT,
            history_key="fruit_history",
            window=FRUIT_ZSCORE_WINDOW,
            tiers=FRUIT_TIERS,
            extreme_threshold=FRUIT_EXTREME_THRESHOLD,
        )
        if fruit_orders:
            orders[FRUIT] = fruit_orders

        fruit_bids, fruit_asks = _book(state, FRUIT)
        fruit_mid = naive_mid(fruit_bids, fruit_asks)
        if fruit_mid is not None:
            tte = _voucher_time_to_expiry(state.timestamp)
            if tte > 0:
                current_deltas = _current_voucher_deltas(state, fruit_mid, tte)
                baseline_exposure = float(state.position.get(FRUIT, 0))
                for strike, delta in current_deltas.items():
                    baseline_exposure += state.position.get(f"{VOUCHER_PREFIX}{strike}", 0) * delta
                running_exposure = baseline_exposure

                for strike in sorted(ACTIVE_VOUCHER_STRIKES):
                    tiers = LIQUID_VOUCHER_TIERS if strike in LIQUID_VOUCHER_STRIKES else ILLIQUID_VOUCHER_TIERS
                    voucher_orders, exposure_delta, _ = _trade_voucher(
                        state,
                        trader_data,
                        strike=strike,
                        fruit_mid=fruit_mid,
                        tte=tte,
                        tiers=tiers,
                        running_exposure=running_exposure,
                    )
                    if voucher_orders:
                        orders[f"{VOUCHER_PREFIX}{strike}"] = voucher_orders
                        running_exposure += exposure_delta
                    else:
                        reduce_order = _reduce_only_order(
                            state, strike=strike, baseline_exposure=baseline_exposure
                        )
                        if reduce_order is not None:
                            orders[f"{VOUCHER_PREFIX}{strike}"] = [reduce_order]
                            running_exposure += reduce_order.quantity * current_deltas.get(strike, 0.0)

        return orders, 0, json.dumps(trader_data)
